version: '3.9'
services:
  caskr-db:
    build: ./Database
    image: postgres:alpine
    container_name: caskr-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: caskr-db
    ports:
      - '5432:5432'
    volumes:
      - ./Database/postgres:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d

  keycloak:
    build: ./Keycloak
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
