export {
  cacheApiResponse,
  getCachedResponse,
  invalidateCache,
  clearApiCache,
  addToSyncQueue,
  getSyncQueue,
  updateSyncItemRetries,
  removeSyncItem,
  getSyncQueueCount,
  cacheEntities,
  getCachedEntities,
  getCachedEntity,
  clearEntityCache,
  isIndexedDBAvailable,
  getStorageEstimate,
  closeDatabase,
  STORES,
} from './offlineStorage'
